language: ruby
rvm:
  - 1.9.3
before_install:
  - export rvmsudo_secure_path=0
  - rvmsudo gem install bundler --no-ri --no-rdoc
  - rvmsudo which gem
  - rvmsudo which ruby
  - rvmsudo rvm info
  - rvmsudo which bundle
  - sudo apt-get update
  - sudo apt-get install libxslt-dev libxml2-dev build-essential
script: bundle exec vagabond kitchen test --platform ubuntu-12.04