before_install:
  - sudo apt-get update
  - sudo ifconfig
  - sudo apt-get install lxc || /bin/true
  - sudo cat /etc/default/lxc
  - sudo ifconfig
  - sudo /etc/init.d/lxc-net start
  - sudo apt-get install --fix-broken
  - sudo ps -AH ux
  - sudo apt-get install lxc
  - sudo add-apt-repository -y ppa:brightbox/ruby-ng-experimental 
  - sudo apt-get update
  - sudo apt-get install ruby1.9.3
  - export PATH=/usr/bin:$PATH
  - sudo apt-get install libxslt-dev libxml2-dev build-essential
  - sudo gem install bundler --no-ri --no-rdoc
  - sudo bundle install
  - sudo apt-get update
script: bundle exec vagabond kitchen test --platform ubuntu-12.04 --debug